// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.oleaster.blemobi.probuf;

public final class LoginProtos {
  private LoginProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.PLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 type = 1;</code>
     *
     * <pre>
     *固定为1
     * </pre>
     */
    int getType();

    /**
     * <code>optional string uuid = 6;</code>
     *
     * <pre>
     *保留2~5用于扩展
     * </pre>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 6;</code>
     *
     * <pre>
     *保留2~5用于扩展
     * </pre>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional string token = 7;</code>
     *
     * <pre>
     *统一访问令牌
     * </pre>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 7;</code>
     *
     * <pre>
     *统一访问令牌
     * </pre>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>optional string name = 8;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 8;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string portrait = 9;</code>
     *
     * <pre>
     *用户头像URL
     * </pre>
     */
    java.lang.String getPortrait();
    /**
     * <code>optional string portrait = 9;</code>
     *
     * <pre>
     *用户头像URL
     * </pre>
     */
    com.google.protobuf.ByteString
        getPortraitBytes();
  }
  /**
   * Protobuf type {@code common.PLogin}
   */
  public  static final class PLogin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.PLogin)
      PLoginOrBuilder {
    // Use PLogin.newBuilder() to construct.
    private PLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PLogin() {
      type_ = 0;
      uuid_ = "";
      token_ = "";
      name_ = "";
      portrait_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              portrait_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oleaster.blemobi.probuf.LoginProtos.internal_static_common_PLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oleaster.blemobi.probuf.LoginProtos.internal_static_common_PLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oleaster.blemobi.probuf.LoginProtos.PLogin.class, com.oleaster.blemobi.probuf.LoginProtos.PLogin.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional int32 type = 1;</code>
     *
     * <pre>
     *固定为1
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int UUID_FIELD_NUMBER = 6;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 6;</code>
     *
     * <pre>
     *保留2~5用于扩展
     * </pre>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string uuid = 6;</code>
     *
     * <pre>
     *保留2~5用于扩展
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 7;
    private volatile java.lang.Object token_;
    /**
     * <code>optional string token = 7;</code>
     *
     * <pre>
     *统一访问令牌
     * </pre>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>optional string token = 7;</code>
     *
     * <pre>
     *统一访问令牌
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 8;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 8;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 8;</code>
     *
     * <pre>
     *用户昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORTRAIT_FIELD_NUMBER = 9;
    private volatile java.lang.Object portrait_;
    /**
     * <code>optional string portrait = 9;</code>
     *
     * <pre>
     *用户头像URL
     * </pre>
     */
    public java.lang.String getPortrait() {
      java.lang.Object ref = portrait_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        portrait_ = s;
        return s;
      }
    }
    /**
     * <code>optional string portrait = 9;</code>
     *
     * <pre>
     *用户头像URL
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPortraitBytes() {
      java.lang.Object ref = portrait_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        portrait_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, uuid_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, token_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, name_);
      }
      if (!getPortraitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, portrait_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, uuid_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, token_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, name_);
      }
      if (!getPortraitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, portrait_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.oleaster.blemobi.probuf.LoginProtos.PLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oleaster.blemobi.probuf.LoginProtos.PLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oleaster.blemobi.probuf.LoginProtos.PLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oleaster.blemobi.probuf.LoginProtos.PLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oleaster.blemobi.probuf.LoginProtos.PLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.LoginProtos.PLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.oleaster.blemobi.probuf.LoginProtos.PLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.LoginProtos.PLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.oleaster.blemobi.probuf.LoginProtos.PLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.LoginProtos.PLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oleaster.blemobi.probuf.LoginProtos.PLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.PLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.PLogin)
        com.oleaster.blemobi.probuf.LoginProtos.PLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oleaster.blemobi.probuf.LoginProtos.internal_static_common_PLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oleaster.blemobi.probuf.LoginProtos.internal_static_common_PLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oleaster.blemobi.probuf.LoginProtos.PLogin.class, com.oleaster.blemobi.probuf.LoginProtos.PLogin.Builder.class);
      }

      // Construct using com.oleaster.blemobi.probuf.LoginProtos.PLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        uuid_ = "";

        token_ = "";

        name_ = "";

        portrait_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oleaster.blemobi.probuf.LoginProtos.internal_static_common_PLogin_descriptor;
      }

      public com.oleaster.blemobi.probuf.LoginProtos.PLogin getDefaultInstanceForType() {
        return com.oleaster.blemobi.probuf.LoginProtos.PLogin.getDefaultInstance();
      }

      public com.oleaster.blemobi.probuf.LoginProtos.PLogin build() {
        com.oleaster.blemobi.probuf.LoginProtos.PLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oleaster.blemobi.probuf.LoginProtos.PLogin buildPartial() {
        com.oleaster.blemobi.probuf.LoginProtos.PLogin result = new com.oleaster.blemobi.probuf.LoginProtos.PLogin(this);
        result.type_ = type_;
        result.uuid_ = uuid_;
        result.token_ = token_;
        result.name_ = name_;
        result.portrait_ = portrait_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oleaster.blemobi.probuf.LoginProtos.PLogin) {
          return mergeFrom((com.oleaster.blemobi.probuf.LoginProtos.PLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oleaster.blemobi.probuf.LoginProtos.PLogin other) {
        if (other == com.oleaster.blemobi.probuf.LoginProtos.PLogin.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getPortrait().isEmpty()) {
          portrait_ = other.portrait_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oleaster.blemobi.probuf.LoginProtos.PLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oleaster.blemobi.probuf.LoginProtos.PLogin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>optional int32 type = 1;</code>
       *
       * <pre>
       *固定为1
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 1;</code>
       *
       * <pre>
       *固定为1
       * </pre>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 1;</code>
       *
       * <pre>
       *固定为1
       * </pre>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 6;</code>
       *
       * <pre>
       *保留2~5用于扩展
       * </pre>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 6;</code>
       *
       * <pre>
       *保留2~5用于扩展
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 6;</code>
       *
       * <pre>
       *保留2~5用于扩展
       * </pre>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 6;</code>
       *
       * <pre>
       *保留2~5用于扩展
       * </pre>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 6;</code>
       *
       * <pre>
       *保留2~5用于扩展
       * </pre>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 7;</code>
       *
       * <pre>
       *统一访问令牌
       * </pre>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 7;</code>
       *
       * <pre>
       *统一访问令牌
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 7;</code>
       *
       * <pre>
       *统一访问令牌
       * </pre>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 7;</code>
       *
       * <pre>
       *统一访问令牌
       * </pre>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 7;</code>
       *
       * <pre>
       *统一访问令牌
       * </pre>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 8;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 8;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 8;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 8;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 8;</code>
       *
       * <pre>
       *用户昵称
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object portrait_ = "";
      /**
       * <code>optional string portrait = 9;</code>
       *
       * <pre>
       *用户头像URL
       * </pre>
       */
      public java.lang.String getPortrait() {
        java.lang.Object ref = portrait_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          portrait_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string portrait = 9;</code>
       *
       * <pre>
       *用户头像URL
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPortraitBytes() {
        java.lang.Object ref = portrait_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          portrait_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string portrait = 9;</code>
       *
       * <pre>
       *用户头像URL
       * </pre>
       */
      public Builder setPortrait(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        portrait_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string portrait = 9;</code>
       *
       * <pre>
       *用户头像URL
       * </pre>
       */
      public Builder clearPortrait() {
        
        portrait_ = getDefaultInstance().getPortrait();
        onChanged();
        return this;
      }
      /**
       * <code>optional string portrait = 9;</code>
       *
       * <pre>
       *用户头像URL
       * </pre>
       */
      public Builder setPortraitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        portrait_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:common.PLogin)
    }

    // @@protoc_insertion_point(class_scope:common.PLogin)
    private static final com.oleaster.blemobi.probuf.LoginProtos.PLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oleaster.blemobi.probuf.LoginProtos.PLogin();
    }

    public static com.oleaster.blemobi.probuf.LoginProtos.PLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PLogin>
        PARSER = new com.google.protobuf.AbstractParser<PLogin>() {
      public PLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PLogin(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<PLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PLogin> getParserForType() {
      return PARSER;
    }

    public com.oleaster.blemobi.probuf.LoginProtos.PLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.PUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 type = 1;</code>
     *
     * <pre>
     *固定为2
     * </pre>
     */
    int getType();

    /**
     * <code>optional string nickname = 6;</code>
     */
    java.lang.String getNickname();
    /**
     * <code>optional string nickname = 6;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>optional string realname = 7;</code>
     */
    java.lang.String getRealname();
    /**
     * <code>optional string realname = 7;</code>
     */
    com.google.protobuf.ByteString
        getRealnameBytes();

    /**
     * <code>optional string portrait = 8;</code>
     */
    java.lang.String getPortrait();
    /**
     * <code>optional string portrait = 8;</code>
     */
    com.google.protobuf.ByteString
        getPortraitBytes();

    /**
     * <code>optional int32 gender = 9;</code>
     *
     * <pre>
     *性别 0女，1男
     * </pre>
     */
    int getGender();

    /**
     * <code>optional string birthday = 10;</code>
     */
    java.lang.String getBirthday();
    /**
     * <code>optional string birthday = 10;</code>
     */
    com.google.protobuf.ByteString
        getBirthdayBytes();

    /**
     * <code>optional string email = 11;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 11;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>optional string cellphone = 12;</code>
     */
    java.lang.String getCellphone();
    /**
     * <code>optional string cellphone = 12;</code>
     */
    com.google.protobuf.ByteString
        getCellphoneBytes();
  }
  /**
   * Protobuf type {@code common.PUser}
   */
  public  static final class PUser extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.PUser)
      PUserOrBuilder {
    // Use PUser.newBuilder() to construct.
    private PUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PUser() {
      type_ = 0;
      nickname_ = "";
      realname_ = "";
      portrait_ = "";
      gender_ = 0;
      birthday_ = "";
      email_ = "";
      cellphone_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              nickname_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              realname_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              portrait_ = s;
              break;
            }
            case 72: {

              gender_ = input.readInt32();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              birthday_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              cellphone_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oleaster.blemobi.probuf.LoginProtos.internal_static_common_PUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oleaster.blemobi.probuf.LoginProtos.internal_static_common_PUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oleaster.blemobi.probuf.LoginProtos.PUser.class, com.oleaster.blemobi.probuf.LoginProtos.PUser.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional int32 type = 1;</code>
     *
     * <pre>
     *固定为2
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int NICKNAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object nickname_;
    /**
     * <code>optional string nickname = 6;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      }
    }
    /**
     * <code>optional string nickname = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REALNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object realname_;
    /**
     * <code>optional string realname = 7;</code>
     */
    public java.lang.String getRealname() {
      java.lang.Object ref = realname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        realname_ = s;
        return s;
      }
    }
    /**
     * <code>optional string realname = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRealnameBytes() {
      java.lang.Object ref = realname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORTRAIT_FIELD_NUMBER = 8;
    private volatile java.lang.Object portrait_;
    /**
     * <code>optional string portrait = 8;</code>
     */
    public java.lang.String getPortrait() {
      java.lang.Object ref = portrait_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        portrait_ = s;
        return s;
      }
    }
    /**
     * <code>optional string portrait = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPortraitBytes() {
      java.lang.Object ref = portrait_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        portrait_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 9;
    private int gender_;
    /**
     * <code>optional int32 gender = 9;</code>
     *
     * <pre>
     *性别 0女，1男
     * </pre>
     */
    public int getGender() {
      return gender_;
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 10;
    private volatile java.lang.Object birthday_;
    /**
     * <code>optional string birthday = 10;</code>
     */
    public java.lang.String getBirthday() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthday_ = s;
        return s;
      }
    }
    /**
     * <code>optional string birthday = 10;</code>
     */
    public com.google.protobuf.ByteString
        getBirthdayBytes() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthday_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 11;
    private volatile java.lang.Object email_;
    /**
     * <code>optional string email = 11;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>optional string email = 11;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CELLPHONE_FIELD_NUMBER = 12;
    private volatile java.lang.Object cellphone_;
    /**
     * <code>optional string cellphone = 12;</code>
     */
    public java.lang.String getCellphone() {
      java.lang.Object ref = cellphone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cellphone_ = s;
        return s;
      }
    }
    /**
     * <code>optional string cellphone = 12;</code>
     */
    public com.google.protobuf.ByteString
        getCellphoneBytes() {
      java.lang.Object ref = cellphone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cellphone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (!getNicknameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, nickname_);
      }
      if (!getRealnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, realname_);
      }
      if (!getPortraitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, portrait_);
      }
      if (gender_ != 0) {
        output.writeInt32(9, gender_);
      }
      if (!getBirthdayBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, birthday_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 11, email_);
      }
      if (!getCellphoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 12, cellphone_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (!getNicknameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, nickname_);
      }
      if (!getRealnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, realname_);
      }
      if (!getPortraitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, portrait_);
      }
      if (gender_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, gender_);
      }
      if (!getBirthdayBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, birthday_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(11, email_);
      }
      if (!getCellphoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(12, cellphone_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.oleaster.blemobi.probuf.LoginProtos.PUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oleaster.blemobi.probuf.LoginProtos.PUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oleaster.blemobi.probuf.LoginProtos.PUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oleaster.blemobi.probuf.LoginProtos.PUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oleaster.blemobi.probuf.LoginProtos.PUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.LoginProtos.PUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.oleaster.blemobi.probuf.LoginProtos.PUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.LoginProtos.PUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.oleaster.blemobi.probuf.LoginProtos.PUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.LoginProtos.PUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oleaster.blemobi.probuf.LoginProtos.PUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.PUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.PUser)
        com.oleaster.blemobi.probuf.LoginProtos.PUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oleaster.blemobi.probuf.LoginProtos.internal_static_common_PUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oleaster.blemobi.probuf.LoginProtos.internal_static_common_PUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oleaster.blemobi.probuf.LoginProtos.PUser.class, com.oleaster.blemobi.probuf.LoginProtos.PUser.Builder.class);
      }

      // Construct using com.oleaster.blemobi.probuf.LoginProtos.PUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        nickname_ = "";

        realname_ = "";

        portrait_ = "";

        gender_ = 0;

        birthday_ = "";

        email_ = "";

        cellphone_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oleaster.blemobi.probuf.LoginProtos.internal_static_common_PUser_descriptor;
      }

      public com.oleaster.blemobi.probuf.LoginProtos.PUser getDefaultInstanceForType() {
        return com.oleaster.blemobi.probuf.LoginProtos.PUser.getDefaultInstance();
      }

      public com.oleaster.blemobi.probuf.LoginProtos.PUser build() {
        com.oleaster.blemobi.probuf.LoginProtos.PUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oleaster.blemobi.probuf.LoginProtos.PUser buildPartial() {
        com.oleaster.blemobi.probuf.LoginProtos.PUser result = new com.oleaster.blemobi.probuf.LoginProtos.PUser(this);
        result.type_ = type_;
        result.nickname_ = nickname_;
        result.realname_ = realname_;
        result.portrait_ = portrait_;
        result.gender_ = gender_;
        result.birthday_ = birthday_;
        result.email_ = email_;
        result.cellphone_ = cellphone_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oleaster.blemobi.probuf.LoginProtos.PUser) {
          return mergeFrom((com.oleaster.blemobi.probuf.LoginProtos.PUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oleaster.blemobi.probuf.LoginProtos.PUser other) {
        if (other == com.oleaster.blemobi.probuf.LoginProtos.PUser.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          onChanged();
        }
        if (!other.getRealname().isEmpty()) {
          realname_ = other.realname_;
          onChanged();
        }
        if (!other.getPortrait().isEmpty()) {
          portrait_ = other.portrait_;
          onChanged();
        }
        if (other.getGender() != 0) {
          setGender(other.getGender());
        }
        if (!other.getBirthday().isEmpty()) {
          birthday_ = other.birthday_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getCellphone().isEmpty()) {
          cellphone_ = other.cellphone_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oleaster.blemobi.probuf.LoginProtos.PUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oleaster.blemobi.probuf.LoginProtos.PUser) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>optional int32 type = 1;</code>
       *
       * <pre>
       *固定为2
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 1;</code>
       *
       * <pre>
       *固定为2
       * </pre>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 1;</code>
       *
       * <pre>
       *固定为2
       * </pre>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>optional string nickname = 6;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickname = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickname = 6;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 6;</code>
       */
      public Builder clearNickname() {
        
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 6;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object realname_ = "";
      /**
       * <code>optional string realname = 7;</code>
       */
      public java.lang.String getRealname() {
        java.lang.Object ref = realname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          realname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string realname = 7;</code>
       */
      public com.google.protobuf.ByteString
          getRealnameBytes() {
        java.lang.Object ref = realname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          realname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string realname = 7;</code>
       */
      public Builder setRealname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        realname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string realname = 7;</code>
       */
      public Builder clearRealname() {
        
        realname_ = getDefaultInstance().getRealname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string realname = 7;</code>
       */
      public Builder setRealnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        realname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object portrait_ = "";
      /**
       * <code>optional string portrait = 8;</code>
       */
      public java.lang.String getPortrait() {
        java.lang.Object ref = portrait_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          portrait_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string portrait = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPortraitBytes() {
        java.lang.Object ref = portrait_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          portrait_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string portrait = 8;</code>
       */
      public Builder setPortrait(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        portrait_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string portrait = 8;</code>
       */
      public Builder clearPortrait() {
        
        portrait_ = getDefaultInstance().getPortrait();
        onChanged();
        return this;
      }
      /**
       * <code>optional string portrait = 8;</code>
       */
      public Builder setPortraitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        portrait_ = value;
        onChanged();
        return this;
      }

      private int gender_ ;
      /**
       * <code>optional int32 gender = 9;</code>
       *
       * <pre>
       *性别 0女，1男
       * </pre>
       */
      public int getGender() {
        return gender_;
      }
      /**
       * <code>optional int32 gender = 9;</code>
       *
       * <pre>
       *性别 0女，1男
       * </pre>
       */
      public Builder setGender(int value) {
        
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gender = 9;</code>
       *
       * <pre>
       *性别 0女，1男
       * </pre>
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object birthday_ = "";
      /**
       * <code>optional string birthday = 10;</code>
       */
      public java.lang.String getBirthday() {
        java.lang.Object ref = birthday_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          birthday_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string birthday = 10;</code>
       */
      public com.google.protobuf.ByteString
          getBirthdayBytes() {
        java.lang.Object ref = birthday_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthday_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string birthday = 10;</code>
       */
      public Builder setBirthday(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        birthday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string birthday = 10;</code>
       */
      public Builder clearBirthday() {
        
        birthday_ = getDefaultInstance().getBirthday();
        onChanged();
        return this;
      }
      /**
       * <code>optional string birthday = 10;</code>
       */
      public Builder setBirthdayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        birthday_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 11;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cellphone_ = "";
      /**
       * <code>optional string cellphone = 12;</code>
       */
      public java.lang.String getCellphone() {
        java.lang.Object ref = cellphone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cellphone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cellphone = 12;</code>
       */
      public com.google.protobuf.ByteString
          getCellphoneBytes() {
        java.lang.Object ref = cellphone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cellphone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cellphone = 12;</code>
       */
      public Builder setCellphone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cellphone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cellphone = 12;</code>
       */
      public Builder clearCellphone() {
        
        cellphone_ = getDefaultInstance().getCellphone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cellphone = 12;</code>
       */
      public Builder setCellphoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cellphone_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:common.PUser)
    }

    // @@protoc_insertion_point(class_scope:common.PUser)
    private static final com.oleaster.blemobi.probuf.LoginProtos.PUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oleaster.blemobi.probuf.LoginProtos.PUser();
    }

    public static com.oleaster.blemobi.probuf.LoginProtos.PUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PUser>
        PARSER = new com.google.protobuf.AbstractParser<PUser>() {
      public PUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PUser(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<PUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PUser> getParserForType() {
      return PARSER;
    }

    public com.oleaster.blemobi.probuf.LoginProtos.PUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_PLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_PLogin_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_PUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_PUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\022\006common\"S\n\006PLogin\022\014\n\004type\030" +
      "\001 \001(\005\022\014\n\004uuid\030\006 \001(\t\022\r\n\005token\030\007 \001(\t\022\014\n\004na" +
      "me\030\010 \001(\t\022\020\n\010portrait\030\t \001(\t\"\217\001\n\005PUser\022\014\n\004" +
      "type\030\001 \001(\005\022\020\n\010nickname\030\006 \001(\t\022\020\n\010realname" +
      "\030\007 \001(\t\022\020\n\010portrait\030\010 \001(\t\022\016\n\006gender\030\t \001(\005" +
      "\022\020\n\010birthday\030\n \001(\t\022\r\n\005email\030\013 \001(\t\022\021\n\tcel" +
      "lphone\030\014 \001(\tB*\n\033com.oleaster.blemobi.pro" +
      "bufB\013LoginProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_PLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_PLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_PLogin_descriptor,
        new java.lang.String[] { "Type", "Uuid", "Token", "Name", "Portrait", });
    internal_static_common_PUser_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_PUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_PUser_descriptor,
        new java.lang.String[] { "Type", "Nickname", "Realname", "Portrait", "Gender", "Birthday", "Email", "Cellphone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
