// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: result.proto

package com.oleaster.blemobi.probuf;

public final class ResultProtos {
  private ResultProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.PResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 type = 1;</code>
     *
     * <pre>
     *固定为0
     * </pre>
     */
    int getType();

    /**
     * <code>optional int32 errorCode = 2;</code>
     *
     * <pre>
     *错误码：0为正确，其他均为出错
     * </pre>
     */
    int getErrorCode();

    /**
     * <code>optional string errorMsg = 3;</code>
     *
     * <pre>
     *错误描述信息
     * </pre>
     */
    java.lang.String getErrorMsg();
    /**
     * <code>optional string errorMsg = 3;</code>
     *
     * <pre>
     *错误描述信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();

    /**
     * <code>optional string extraInfo = 4;</code>
     *
     * <pre>
     *额外信息
     * </pre>
     */
    java.lang.String getExtraInfo();
    /**
     * <code>optional string extraInfo = 4;</code>
     *
     * <pre>
     *额外信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getExtraInfoBytes();
  }
  /**
   * Protobuf type {@code common.PResult}
   *
   * <pre>
   * 通用操作结果返回
   * </pre>
   */
  public  static final class PResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.PResult)
      PResultOrBuilder {
    // Use PResult.newBuilder() to construct.
    private PResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PResult() {
      type_ = 0;
      errorCode_ = 0;
      errorMsg_ = "";
      extraInfo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 16: {

              errorCode_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errorMsg_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              extraInfo_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oleaster.blemobi.probuf.ResultProtos.internal_static_common_PResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oleaster.blemobi.probuf.ResultProtos.internal_static_common_PResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oleaster.blemobi.probuf.ResultProtos.PResult.class, com.oleaster.blemobi.probuf.ResultProtos.PResult.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional int32 type = 1;</code>
     *
     * <pre>
     *固定为0
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 2;</code>
     *
     * <pre>
     *错误码：0为正确，其他均为出错
     * </pre>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int ERRORMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object errorMsg_;
    /**
     * <code>optional string errorMsg = 3;</code>
     *
     * <pre>
     *错误描述信息
     * </pre>
     */
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string errorMsg = 3;</code>
     *
     * <pre>
     *错误描述信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRAINFO_FIELD_NUMBER = 4;
    private volatile java.lang.Object extraInfo_;
    /**
     * <code>optional string extraInfo = 4;</code>
     *
     * <pre>
     *额外信息
     * </pre>
     */
    public java.lang.String getExtraInfo() {
      java.lang.Object ref = extraInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extraInfo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string extraInfo = 4;</code>
     *
     * <pre>
     *额外信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getExtraInfoBytes() {
      java.lang.Object ref = extraInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extraInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (errorCode_ != 0) {
        output.writeInt32(2, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, errorMsg_);
      }
      if (!getExtraInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, extraInfo_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorCode_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, errorMsg_);
      }
      if (!getExtraInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, extraInfo_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.oleaster.blemobi.probuf.ResultProtos.PResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oleaster.blemobi.probuf.ResultProtos.PResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oleaster.blemobi.probuf.ResultProtos.PResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oleaster.blemobi.probuf.ResultProtos.PResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oleaster.blemobi.probuf.ResultProtos.PResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.ResultProtos.PResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.oleaster.blemobi.probuf.ResultProtos.PResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.ResultProtos.PResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.oleaster.blemobi.probuf.ResultProtos.PResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.ResultProtos.PResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oleaster.blemobi.probuf.ResultProtos.PResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.PResult}
     *
     * <pre>
     * 通用操作结果返回
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.PResult)
        com.oleaster.blemobi.probuf.ResultProtos.PResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oleaster.blemobi.probuf.ResultProtos.internal_static_common_PResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oleaster.blemobi.probuf.ResultProtos.internal_static_common_PResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oleaster.blemobi.probuf.ResultProtos.PResult.class, com.oleaster.blemobi.probuf.ResultProtos.PResult.Builder.class);
      }

      // Construct using com.oleaster.blemobi.probuf.ResultProtos.PResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        errorCode_ = 0;

        errorMsg_ = "";

        extraInfo_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oleaster.blemobi.probuf.ResultProtos.internal_static_common_PResult_descriptor;
      }

      public com.oleaster.blemobi.probuf.ResultProtos.PResult getDefaultInstanceForType() {
        return com.oleaster.blemobi.probuf.ResultProtos.PResult.getDefaultInstance();
      }

      public com.oleaster.blemobi.probuf.ResultProtos.PResult build() {
        com.oleaster.blemobi.probuf.ResultProtos.PResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oleaster.blemobi.probuf.ResultProtos.PResult buildPartial() {
        com.oleaster.blemobi.probuf.ResultProtos.PResult result = new com.oleaster.blemobi.probuf.ResultProtos.PResult(this);
        result.type_ = type_;
        result.errorCode_ = errorCode_;
        result.errorMsg_ = errorMsg_;
        result.extraInfo_ = extraInfo_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oleaster.blemobi.probuf.ResultProtos.PResult) {
          return mergeFrom((com.oleaster.blemobi.probuf.ResultProtos.PResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oleaster.blemobi.probuf.ResultProtos.PResult other) {
        if (other == com.oleaster.blemobi.probuf.ResultProtos.PResult.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        if (!other.getErrorMsg().isEmpty()) {
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        if (!other.getExtraInfo().isEmpty()) {
          extraInfo_ = other.extraInfo_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oleaster.blemobi.probuf.ResultProtos.PResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oleaster.blemobi.probuf.ResultProtos.PResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>optional int32 type = 1;</code>
       *
       * <pre>
       *固定为0
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 1;</code>
       *
       * <pre>
       *固定为0
       * </pre>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 1;</code>
       *
       * <pre>
       *固定为0
       * </pre>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 2;</code>
       *
       * <pre>
       *错误码：0为正确，其他均为出错
       * </pre>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 2;</code>
       *
       * <pre>
       *错误码：0为正确，其他均为出错
       * </pre>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 2;</code>
       *
       * <pre>
       *错误码：0为正确，其他均为出错
       * </pre>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorMsg_ = "";
      /**
       * <code>optional string errorMsg = 3;</code>
       *
       * <pre>
       *错误描述信息
       * </pre>
       */
      public java.lang.String getErrorMsg() {
        java.lang.Object ref = errorMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMsg = 3;</code>
       *
       * <pre>
       *错误描述信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        java.lang.Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMsg = 3;</code>
       *
       * <pre>
       *错误描述信息
       * </pre>
       */
      public Builder setErrorMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMsg = 3;</code>
       *
       * <pre>
       *错误描述信息
       * </pre>
       */
      public Builder clearErrorMsg() {
        
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMsg = 3;</code>
       *
       * <pre>
       *错误描述信息
       * </pre>
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object extraInfo_ = "";
      /**
       * <code>optional string extraInfo = 4;</code>
       *
       * <pre>
       *额外信息
       * </pre>
       */
      public java.lang.String getExtraInfo() {
        java.lang.Object ref = extraInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extraInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string extraInfo = 4;</code>
       *
       * <pre>
       *额外信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getExtraInfoBytes() {
        java.lang.Object ref = extraInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extraInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string extraInfo = 4;</code>
       *
       * <pre>
       *额外信息
       * </pre>
       */
      public Builder setExtraInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extraInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string extraInfo = 4;</code>
       *
       * <pre>
       *额外信息
       * </pre>
       */
      public Builder clearExtraInfo() {
        
        extraInfo_ = getDefaultInstance().getExtraInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string extraInfo = 4;</code>
       *
       * <pre>
       *额外信息
       * </pre>
       */
      public Builder setExtraInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extraInfo_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:common.PResult)
    }

    // @@protoc_insertion_point(class_scope:common.PResult)
    private static final com.oleaster.blemobi.probuf.ResultProtos.PResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oleaster.blemobi.probuf.ResultProtos.PResult();
    }

    public static com.oleaster.blemobi.probuf.ResultProtos.PResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PResult>
        PARSER = new com.google.protobuf.AbstractParser<PResult>() {
      public PResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PResult(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<PResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PResult> getParserForType() {
      return PARSER;
    }

    public com.oleaster.blemobi.probuf.ResultProtos.PResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.PType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 type = 1;</code>
     */
    int getType();
  }
  /**
   * Protobuf type {@code common.PType}
   *
   * <pre>
   *&#64;note 用于反序列化时，第一次的探索，以进一步判断序列化的数据是什么类型
   *&#64;type 可能出现的结构类型定义
   * </pre>
   */
  public  static final class PType extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.PType)
      PTypeOrBuilder {
    // Use PType.newBuilder() to construct.
    private PType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PType() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oleaster.blemobi.probuf.ResultProtos.internal_static_common_PType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oleaster.blemobi.probuf.ResultProtos.internal_static_common_PType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oleaster.blemobi.probuf.ResultProtos.PType.class, com.oleaster.blemobi.probuf.ResultProtos.PType.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.oleaster.blemobi.probuf.ResultProtos.PType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oleaster.blemobi.probuf.ResultProtos.PType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oleaster.blemobi.probuf.ResultProtos.PType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oleaster.blemobi.probuf.ResultProtos.PType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oleaster.blemobi.probuf.ResultProtos.PType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.ResultProtos.PType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.oleaster.blemobi.probuf.ResultProtos.PType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.ResultProtos.PType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.oleaster.blemobi.probuf.ResultProtos.PType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.oleaster.blemobi.probuf.ResultProtos.PType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oleaster.blemobi.probuf.ResultProtos.PType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.PType}
     *
     * <pre>
     *&#64;note 用于反序列化时，第一次的探索，以进一步判断序列化的数据是什么类型
     *&#64;type 可能出现的结构类型定义
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.PType)
        com.oleaster.blemobi.probuf.ResultProtos.PTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oleaster.blemobi.probuf.ResultProtos.internal_static_common_PType_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oleaster.blemobi.probuf.ResultProtos.internal_static_common_PType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oleaster.blemobi.probuf.ResultProtos.PType.class, com.oleaster.blemobi.probuf.ResultProtos.PType.Builder.class);
      }

      // Construct using com.oleaster.blemobi.probuf.ResultProtos.PType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oleaster.blemobi.probuf.ResultProtos.internal_static_common_PType_descriptor;
      }

      public com.oleaster.blemobi.probuf.ResultProtos.PType getDefaultInstanceForType() {
        return com.oleaster.blemobi.probuf.ResultProtos.PType.getDefaultInstance();
      }

      public com.oleaster.blemobi.probuf.ResultProtos.PType build() {
        com.oleaster.blemobi.probuf.ResultProtos.PType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.oleaster.blemobi.probuf.ResultProtos.PType buildPartial() {
        com.oleaster.blemobi.probuf.ResultProtos.PType result = new com.oleaster.blemobi.probuf.ResultProtos.PType(this);
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oleaster.blemobi.probuf.ResultProtos.PType) {
          return mergeFrom((com.oleaster.blemobi.probuf.ResultProtos.PType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oleaster.blemobi.probuf.ResultProtos.PType other) {
        if (other == com.oleaster.blemobi.probuf.ResultProtos.PType.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.oleaster.blemobi.probuf.ResultProtos.PType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.oleaster.blemobi.probuf.ResultProtos.PType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>optional int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:common.PType)
    }

    // @@protoc_insertion_point(class_scope:common.PType)
    private static final com.oleaster.blemobi.probuf.ResultProtos.PType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oleaster.blemobi.probuf.ResultProtos.PType();
    }

    public static com.oleaster.blemobi.probuf.ResultProtos.PType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PType>
        PARSER = new com.google.protobuf.AbstractParser<PType>() {
      public PType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PType(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<PType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PType> getParserForType() {
      return PARSER;
    }

    public com.oleaster.blemobi.probuf.ResultProtos.PType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_PResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_PResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_PType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_PType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014result.proto\022\006common\"O\n\007PResult\022\014\n\004typ" +
      "e\030\001 \001(\005\022\021\n\terrorCode\030\002 \001(\005\022\020\n\010errorMsg\030\003" +
      " \001(\t\022\021\n\textraInfo\030\004 \001(\t\"\025\n\005PType\022\014\n\004type" +
      "\030\001 \001(\005B+\n\033com.oleaster.blemobi.probufB\014R" +
      "esultProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_PResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_PResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_PResult_descriptor,
        new java.lang.String[] { "Type", "ErrorCode", "ErrorMsg", "ExtraInfo", });
    internal_static_common_PType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_PType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_PType_descriptor,
        new java.lang.String[] { "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
