// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	login.proto
	result.proto

It has these top-level messages:
	PLogin
	PUser
*/
package common

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type PLogin struct {
	Type int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	// 保留2~5用于扩展
	Uuid     string `protobuf:"bytes,6,opt,name=uuid" json:"uuid,omitempty"`
	Token    string `protobuf:"bytes,7,opt,name=token" json:"token,omitempty"`
	Name     string `protobuf:"bytes,8,opt,name=name" json:"name,omitempty"`
	Portrait string `protobuf:"bytes,9,opt,name=portrait" json:"portrait,omitempty"`
}

func (m *PLogin) Reset()         { *m = PLogin{} }
func (m *PLogin) String() string { return proto.CompactTextString(m) }
func (*PLogin) ProtoMessage()    {}

type PUser struct {
	Type      int32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Nickname  string `protobuf:"bytes,6,opt,name=nickname" json:"nickname,omitempty"`
	Realname  string `protobuf:"bytes,7,opt,name=realname" json:"realname,omitempty"`
	Portrait  string `protobuf:"bytes,8,opt,name=portrait" json:"portrait,omitempty"`
	Gender    int32  `protobuf:"varint,9,opt,name=gender" json:"gender,omitempty"`
	Birthday  string `protobuf:"bytes,10,opt,name=birthday" json:"birthday,omitempty"`
	Email     string `protobuf:"bytes,11,opt,name=email" json:"email,omitempty"`
	Cellphone string `protobuf:"bytes,12,opt,name=cellphone" json:"cellphone,omitempty"`
}

func (m *PUser) Reset()         { *m = PUser{} }
func (m *PUser) String() string { return proto.CompactTextString(m) }
func (*PUser) ProtoMessage()    {}
